import Head from 'next/head';
import Image from 'next/image';
import { useCallback, useState } from 'react';
import Submission from '../lib/models/Submission';
import styles from '../lib/styles/Home.module.css';

export default function Home(props) {
	const [newSubmission, setNewSubmission] = useState(null);

	const handleCreateSubmission = useCallback(() => {
		const doCreate = async () => {
			const res = await fetch('/api/submit', {
				method: 'POST',
			});

			if (res.ok) {
				const json = await res.json();
				setNewSubmission(json);
			}
		};

		doCreate();
	}, []);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<button type="button" onClick={handleCreateSubmission}>
					Create submission
				</button>
				<pre>{JSON.stringify(newSubmission, null, 2)}</pre>
				<hr style={{ minWidth: '100vw' }} />
				<pre>{JSON.stringify(props, null, 2)}</pre>
			</main>

			<footer className={styles.footer}>
				Powered by{' '}
				<span className={styles.logo}>
					<Image
						src="/vercel.svg"
						alt="Vercel Logo"
						width={72}
						height={16}
					/>
				</span>
			</footer>
		</div>
	);
}

export async function getServerSideProps(context) {
	const submissions = await Submission.query();

	return {
		props: {
			submissions: submissions.map((submission) => submission.toJSON()),
		},
	};
}
